### ISSUE TITLE
Packaging issues preventing vitest from working

### ISSUE THREAD

**Issue by panthershark** [ekwoka/preact-heroicons#3]
Moved here from https://github.com/graywolftech/react-heroicons/issues/14

----

The error emitted from vitest is 'Error: Failed to resolve entry for package "preact-heroicons". The package may have incorrect main/module/exports specified in its package.json.'

This documents fixes for it. I hacked the package.json and got past the initial error so I think this can be fixed.
https://github.com/sheremet-va/dual-packaging

Here is a small example of the problem:
https://github.com/panthershark/sscce-preact-heroicons-vitest-error

**Comment by ekwoka** [comment]
This is quite weird. I was seeing that error at first with your package. Then I tried to replicate it in another repo and it worked, then came back to your repo and it worked...

**Comment by panthershark** [comment]
If using `npm link`, it might've been a  weird sequence of commands (or maybe vite cache that caused it to use another version or branch?

I often find that npm link can be confusing (even when I used it heavily years ago). 

If installing directly from GitHub, maybe an npm cache issue?

I had the npm cache issue last night. I made a branch in GitHub that has the dist folder checked in so I could install from GitHub to test (and get my build through CI). Each time I updated the branch, I needed to force `npm cache clean` or things acted weird.

**Comment by ekwoka** [comment]
Well, I was doing a install from file.

I'm still investigating, since this is a problem I'd want solved. 

I'm just not sure why, especially if vite can find it normally without issue anyway.

**Comment by panthershark** [comment]
It looks like the upstream repo was created against a proposed spec, then the spec changed. 

Roll-up and webpack might be more gracious, but esbuild is very strict against the official spec.

For example, the module keyword in package.json was replaced with exports. 

I'm at a soccer tournament for the weekend, but I'll try to research this week and reply here.

**Comment by ekwoka** [comment]
Interesting. I hadn't heard about the change in the exports. I just knew `main` and `module`.

**Comment by panthershark** [comment]
I setup a new `main` branch on my fork. It publishes the package to github packages here-  https://github.com/panthershark/preact-heroicons/pkgs/npm/preact-heroicons

This version will work with new jsx-runtime and with vitest. This allowed me to finish migrating to vitest and getting things through my CI pipeline.  :rocket:
